# Generated by Django 5.2 on 2025-05-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firebase_uid',
        ),
    ]
