# Generated by Django 5.2 on 2025-06-12 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studentteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Código o nombre de la asignatura', max_length=100)),
                ('completed_tests', models.IntegerField(default=0, help_text='Número de tests que el estudiante ha finalizado')),
                ('correct_answers', models.IntegerField(default=0, help_text='Total de respuestas correctas hasta ahora')),
                ('total_questions', models.IntegerField(default=0, help_text='Total de preguntas contestadas hasta ahora')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización de este registro')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress Records',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
