# Generated by Django 5.2 on 2025-06-12 21:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentteacher',
            name='active',
        ),
        migrations.AddField(
            model_name='progress',
            name='summaries_generated',
            field=models.IntegerField(default=0, help_text='Total de resúmenes generados por el estudiante en esta asignatura'),
        ),
        migrations.AddField(
            model_name='studentteacher',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentteacher',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Estado de la asignación: pending, accepted o rejected', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default=api.models.generate_invite_code, editable=False, help_text='Código único de 6 dígitos para invitaciones', max_length=6, null=True),
        ),
    ]
