# Generated by Django 5.2 on 2025-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_class_drive_folder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='option_3',
        ),
        migrations.AddField(
            model_name='documents',
            name='subject',
            field=models.CharField(default='Sin asignar', max_length=100),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='correct_option',
            field=models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3')], max_length=1),
        ),
    ]
