# Generated by Django 5.2 on 2025-06-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_documents_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.class'),
        ),
    ]
