# Generated by Django 5.2 on 2025-06-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
