# Generated by Django 5.2 on 2025-06-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
