# Generated by Django 5.2 on 2025-06-11 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='acces_code',
            new_name='access_code',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='user_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='userclass',
            old_name='class_id',
            new_name='class_obj',
        ),
        migrations.RenameField(
            model_name='userclass',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userclass',
            unique_together={('user', 'class_obj')},
        ),
        migrations.RemoveField(
            model_name='documents',
            name='class_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.class'),
        ),
        migrations.AddField(
            model_name='documents',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.class'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('test', 'Test'), ('answer', 'Answer'), ('summary', 'Summary')], max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='users',
            field=models.ManyToManyField(related_name='classes', through='api.UserClass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='selected_option',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C'), ('D', 'Opción D')], max_length=1),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
